/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MySessionsRouteImport } from './routes/my-sessions'
import { Route as MyExercisesRouteImport } from './routes/my-exercises'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoriteSessionsRouteImport } from './routes/favorite-sessions'
import { Route as Exercises_newRouteImport } from './routes/exercises_new'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionPlayerSessionIdRouteImport } from './routes/session-player.$sessionId'
import { Route as SessionDetailsSessionIdRouteImport } from './routes/session-details.$sessionId'

const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MySessionsRoute = MySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const MyExercisesRoute = MyExercisesRouteImport.update({
  id: '/my-exercises',
  path: '/my-exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteSessionsRoute = FavoriteSessionsRouteImport.update({
  id: '/favorite-sessions',
  path: '/favorite-sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const Exercises_newRoute = Exercises_newRouteImport.update({
  id: '/exercises_new',
  path: '/exercises_new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionPlayerSessionIdRoute = SessionPlayerSessionIdRouteImport.update({
  id: '/session-player/$sessionId',
  path: '/session-player/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionDetailsSessionIdRoute = SessionDetailsSessionIdRouteImport.update({
  id: '/session-details/$sessionId',
  path: '/session-details/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/exercises_new': typeof Exercises_newRoute
  '/favorite-sessions': typeof FavoriteSessionsRoute
  '/login': typeof LoginRoute
  '/my-exercises': typeof MyExercisesRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/session-details/$sessionId': typeof SessionDetailsSessionIdRoute
  '/session-player/$sessionId': typeof SessionPlayerSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/exercises_new': typeof Exercises_newRoute
  '/favorite-sessions': typeof FavoriteSessionsRoute
  '/login': typeof LoginRoute
  '/my-exercises': typeof MyExercisesRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/session-details/$sessionId': typeof SessionDetailsSessionIdRoute
  '/session-player/$sessionId': typeof SessionPlayerSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRoute
  '/exercises_new': typeof Exercises_newRoute
  '/favorite-sessions': typeof FavoriteSessionsRoute
  '/login': typeof LoginRoute
  '/my-exercises': typeof MyExercisesRoute
  '/my-sessions': typeof MySessionsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/sessions': typeof SessionsRoute
  '/session-details/$sessionId': typeof SessionDetailsSessionIdRoute
  '/session-player/$sessionId': typeof SessionPlayerSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/exercises_new'
    | '/favorite-sessions'
    | '/login'
    | '/my-exercises'
    | '/my-sessions'
    | '/profile'
    | '/register'
    | '/sessions'
    | '/session-details/$sessionId'
    | '/session-player/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises'
    | '/exercises_new'
    | '/favorite-sessions'
    | '/login'
    | '/my-exercises'
    | '/my-sessions'
    | '/profile'
    | '/register'
    | '/sessions'
    | '/session-details/$sessionId'
    | '/session-player/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/exercises_new'
    | '/favorite-sessions'
    | '/login'
    | '/my-exercises'
    | '/my-sessions'
    | '/profile'
    | '/register'
    | '/sessions'
    | '/session-details/$sessionId'
    | '/session-player/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRoute
  Exercises_newRoute: typeof Exercises_newRoute
  FavoriteSessionsRoute: typeof FavoriteSessionsRoute
  LoginRoute: typeof LoginRoute
  MyExercisesRoute: typeof MyExercisesRoute
  MySessionsRoute: typeof MySessionsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SessionsRoute: typeof SessionsRoute
  SessionDetailsSessionIdRoute: typeof SessionDetailsSessionIdRoute
  SessionPlayerSessionIdRoute: typeof SessionPlayerSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-sessions': {
      id: '/my-sessions'
      path: '/my-sessions'
      fullPath: '/my-sessions'
      preLoaderRoute: typeof MySessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-exercises': {
      id: '/my-exercises'
      path: '/my-exercises'
      fullPath: '/my-exercises'
      preLoaderRoute: typeof MyExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite-sessions': {
      id: '/favorite-sessions'
      path: '/favorite-sessions'
      fullPath: '/favorite-sessions'
      preLoaderRoute: typeof FavoriteSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises_new': {
      id: '/exercises_new'
      path: '/exercises_new'
      fullPath: '/exercises_new'
      preLoaderRoute: typeof Exercises_newRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-player/$sessionId': {
      id: '/session-player/$sessionId'
      path: '/session-player/$sessionId'
      fullPath: '/session-player/$sessionId'
      preLoaderRoute: typeof SessionPlayerSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-details/$sessionId': {
      id: '/session-details/$sessionId'
      path: '/session-details/$sessionId'
      fullPath: '/session-details/$sessionId'
      preLoaderRoute: typeof SessionDetailsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRoute,
  Exercises_newRoute: Exercises_newRoute,
  FavoriteSessionsRoute: FavoriteSessionsRoute,
  LoginRoute: LoginRoute,
  MyExercisesRoute: MyExercisesRoute,
  MySessionsRoute: MySessionsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SessionsRoute: SessionsRoute,
  SessionDetailsSessionIdRoute: SessionDetailsSessionIdRoute,
  SessionPlayerSessionIdRoute: SessionPlayerSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
